application:
  stage: "local"
  host: "127.0.0.1"
  port: ":8080"
pg:
  name: "shop_auth"
  user: "postgres"
  password: "postgres"
  host: "127.0.0.1"
  port: "5432"
  ssl_mode: "disable"
  dsn_template: "host=%s port=%s dbname=%s user=%s password=%s sslmode=%s"